spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

grpc:
  server:
    port: 9090

app:
  jwt:
    # If JWT_SECRET env var is not set, a default value is used in JwtUtil. For production, set JWT_SECRET.
    secret: ${JWT_SECRET:change-me-change-me-change-me-32chars!}
